### ISSUE TITLE
Generating VAMB bins

### ISSUE THREAD

**Issue by mpdoane2** [linsalrob/atavide_lite#5]
Hey Rob

In the bin directory, you have two similar Python scripts: vamb_create_fasta.py and vamb_create_fasta_clusters.py. Which one is most recent? I am currently running vamb_create_fasta_clusters.py on unsplit and split bins on the HPC from the vamb_groups.slurm route. It is taking ages. It is currently at 19 hours at the moment. I'm not sure if this is a resource allocation issue or because there's a lot of data to parse through. 

I have attempted to modify the vamb_create_fasta.py script to test whether it speeds up the process, as it includes a flag for specifying a minimum bin size (20,000 bp). However, the minsize call is throwing an error because of the version of VAMB being used. The update from 4.1.2 to 5.0.4

Error from the 'vamb_create_fasta.py'

Traceback (most recent call last):
  File "/home/doan0033/atavide_lite/bin/vamb_create_fasta.py", line 27, in <module>
    vamb.vambtools.write_bins(
TypeError: write_bins() got an unexpected keyword argument 'minsize'

Thanks
Mike

**Comment by mpdoane2** [comment]
Hey, an update on progress. I was able to generate the individual bin.fna files rapidly by pulling this script from:

https://github.com/RasmussenLab/vamb/blob/master/src/create_fasta.py

The script is updated to work with VAMB 5.0.4. I put this into the atavide_lite pipeline and it worked. It finished generating all the bin.fna in about 2 minutes. I used 8 cpus at 16 gb of memory in the slurm script. 

I will continue to refine the script, and then will send my completed script that worked for the pipeline in another thread.
